export const users = [
  {
    photo: 'images/team-photo/Antonina.jpg',
    photowebp: '..src/images/team-photo/Antonina.webp',
    name: 'Антоніна Іванець',
    position: 'team leader',
    socialmedia: '',
    github: 'https://github.com/AntoninaDanylchenko',
    giticon: '..src/images/team-photo/symbol.defs.svg##icon-github',
  },
  {
    photo: '../src/images/team-photo/AndriyK.jpg',
    name: 'Андрій Корчевський',
    position: 'scrum master',
    socialmedia: '',
    github: 'https://github.com/Salamandero',
  },
  {
    photo: './src/images/team-photo/Vlad.jpg',
    name: 'Владислав Пліско',
    position: '',
    socialmedia: '',
    github: '',
  },
  {
    photo: './src/images/team-photo/AndriyL.jpg',
    name: 'Андрій Лопський',
    position: '',
    socialmedia: '',
    github: 'https://github.com/Andriy19990',
  },
  {
    photo: '',
    name: 'Оксана Богатинська',
    position: '',
    socialmedia: '',
    github: '',
  },
  {
    photo: './src/images/team-photo/Yuriy.jpg',
    name: 'Юрій',
    position: '',
    socialmedia: '',
    github: '',
  },
  {
    photo: '',
    name: 'Володимир Олексюк',
    position: '',
    socialmedia: '',
    github: '',
  },
  {
    photo: '',
    name: 'Анна Юрчук',
    position: '',
    socialmedia: '',
    github: 'https://github.com/Ann-Yurchuk',
  },
  {
    photo: './src/images/team-photo/YuriyTk.jpg',
    name: 'Юрій Ткаченко',
    position: '',
    socialmedia: '',
    github: 'https://github.com/Tkachenko-Yuriy',
  },
  {
    photo: '',
    name: 'Валентин Подріз',
    position: '',
    socialmedia: '',
    github: 'https://github.com/valentynPodriz',
  },
  {
    photo: './src/images/team-photo/NikitaMor.jpg',
    name: 'Микита Мор...',
    position: '',
    socialmedia: '',
    github: 'https://github.com/WhyNikuta',
  },
  {
    photo: '',
    name: 'Наталія Максимейко',
    position: '',
    socialmedia: '',
    github: 'https://github.com/nataliiamax',
  },
];
