
export const users = [
	{photo: 'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/AntoninaI.jpg',
		   name: 'Antonina Ivanets',
  position: 'team leader',
	   socialmedia:'https://raw.githubusercontent.com/AntoninaDanylchenko/team-project-js/main/src/images/icon-git.svg#icon-github',
	   github:'https://github.com/AntoninaDanylchenko',
	   },
	   {
		   photo:'https://raw.githubusercontent.com/AntoninaDanylchenko/team-project-js/main/src/images/team-photo/AndriyK.webp',
		   name: 'Andrew Korchevskiy',
	   position: 'scrum master',
	   socialmedia:'https://raw.githubusercontent.com/AntoninaDanylchenko/team-project-js/main/src/images/icon-git.svg#icon-github',
	   github:'https://github.com/Salamandero',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Vlad.jpg',
		   name: 'Vladislav Plisko',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/litghning',
	   },
	   {photo:'https://raw.githubusercontent.com/AntoninaDanylchenko/team-project-js/main/src/images/team-photo/AndriyL.webp',
		   name: 'Andriy Lopsky',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Andriy19990',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Oksana.jpg',
		   name: 'Oksana Bohatynska',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Bohatynska',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Yuriy.jpg',
		   name: 'Yuriy',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/YurGoV',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Vova.jpg',
		   name: 'Volodymyr Oleksyuk',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Olevova',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Ann.jpg',
		   name: 'Ann Yurchuk',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Ann-Yurchuk',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/YuriyT.jpg',
		   name: 'Yuriy Tkachenko',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Tkachenko-Yuriy',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Valentyn.jpg',
		   name: 'Valentyn Podriz',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/valentynPodriz',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/NikitaMor.jpg',
		   name: 'Nikita Mor',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/WhyNikuta',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Nataliia.jpg',
		   name: 'Nataliia Maksymeiko',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/nataliiamax',
	   },
	 
   ]
