
export const users = [

	{photo: 'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/AntoninaI.jpg',
		   name: 'Антоніна Іванець',
	   position: 'team leader',
	   socialmedia:'',
	   github:'https://github.com/AntoninaDanylchenko',
	   },
	   {
		   photo:'https://raw.githubusercontent.com/AntoninaDanylchenko/team-project-js/main/src/images/team-photo/AndriyK.webp',
		   name: 'Андрій Корчевський',
	   position: 'scrum master',
	   socialmedia:'',
	   github:'https://github.com/Salamandero',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Vlad.jpg',
		   name: 'Владислав Пліско',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/litghning',
	   },
	   {photo:'https://raw.githubusercontent.com/AntoninaDanylchenko/team-project-js/main/src/images/team-photo/AndriyL.webp',
		   name: 'Андрій Лопський',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Andriy19990',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Oksana.jpg',
		   name: 'Оксана Богатинська',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Bohatynska',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Yuriy.jpg',
		   name: 'Юрій',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/YurGoV',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Vova.jpg',
		   name: 'Володимир Олексюк',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Olevova',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Ann.jpg',
		   name: 'Анна Юрчук',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Ann-Yurchuk',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/YuriyT.jpg',
		   name: 'Юрій Ткаченко',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/Tkachenko-Yuriy',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Valentyn.jpg',
		   name: 'Валентин Подріз',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/valentynPodriz',
	   },
	   {photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/NikitaMor.jpg',
		   name: 'Микита Мор',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/WhyNikuta',
	   },
	   {
		   photo:'https://github.com/AntoninaDanylchenko/team-project-js/raw/main/src/images/team-photo/Nataliia.jpg',
		   name: 'Наталія Максимейко',
	   position: 'developer',
	   socialmedia:'',
	   github:'https://github.com/nataliiamax',
	   },
	 
   ]
